= Agile Integration Advanced Lab 11 - Camel K Lab

In this lab, you set up Apache Camel K, to be used as the serverless Camel Development environment on Red Hat OpenShift Container Platform.
Camel K is an alternative runtime to Red Hat Fuse On OpenShift, where Apache Camel routes can now be built and deployed to Red Hat OpenShift Container Platform, using Kubernetes as the application runtime.
You will test various implementations of Camel routes, in Groovy, Javascript and Java format.


[type=walkthroughResource,serviceName=openshift]
.OpenShift
****
* link:{openshift-host}[Openshift Console, window="_blank"]

****

[type=walkthroughResource]
.Useful Resources
****
* link:https://camel.apache.org/camel-k/latest/index.html[Apache Camel K, window="_blank"]
* link:https://knative.dev/docs[Knative Documentation, window="_blank"]
****

== Lab Goals

* Install the Camel K CLI Tool
* Deploy a Camel K Operator on the Red Hat OpenShift Container Platform environment
* Build and deploy several Apache Camel Routes on the Red Hat OpenShift Container Platform environment
* Observe test results from the deployed Apache Camel Routes

[time=45]
== Environment Setup

In this lab, you set up Apache Camel K (aka Kamel), to be used as the serverless test and development environment for Apache Camel projects, on Red Hat OpenShift Container Platform.

Camel K utilizes a operator, which provides the serverless application development framework support, within a Kubernetes-based platform - for building, deploying, and managing modern serverless workloads.
You will deploy the Camel K operator first, before you can build, deploy and test any Apache Camel routes.

To learn more about what an operator is, refer to the link:https://github.com/operator-framework/getting-started[Operator Framework Getting Started Guide].

=== Login to OpenShift Container Platform

. Click on the link:{openshift-host}[OpenShift Console, window="_blank"] to open the `OpenShift Console`.
. You should login with the following credentials:
.. *Username*: `{user-sanitized-username}`
.. *Password*: `openshift`

[type=verification]
Were you able to login to the OpenShift Console?

. Perform a command-line login using .
. You should login with the following credentials:
.. *Username*: `{user-sanitized-username}`
.. *Password*: `openshift`

. On your desktop, open a terminal shell using, for example, PuTTY for Windows.
. In that terminal, login to your OCP instance by copying the login command from the OpenShift console.
+
------
Authentication required for https://master.demo-e61f.openshiftworkshop.com:443 (openshift)
Password:
Login successful.
------
+
NOTE: A successful logon results in a similar message, such as the one shown above.

[type=verification]
Were you able to login to the Red Hat OpenShift Container Platform environment via command line?

* Next, create the project in Red Hat OpenShift Container Platform that will contain both the Camel K Operator and the Apache Camel routes.
. Use the following command to create a new namespace:
+
[subs="attributes"]
----
oc new-project {user-sanitized-username}-camelk

----
+
[type=verification]
Is the new project in OpenShift created successfully?

=== Interact with the Camel K CLI Tool

* In this exercise, you download the Camel K CLI Tool and begin interacting with it.

. Download the archive containing the latest *Camel K* CLI Tool link:https://github.com/apache/camel-k/releases[release] on your workstation.
+
NOTE: A possible method to perform this download can be:
----
wget https://github.com/apache/camel-k/releases/download/1.0.0-M4/camel-k-client-1.0.0-M4-linux-64bit.tar.gz
----

* Now, proceed with environmental variable setup.

. While in the directory containing the CLI Tool, retrieve the path using the command `pwd`.
. Update the PATH environment variable, containing the path to the *Camel K* CLI Tool.
+
----
pwd
<path of Camel K CLI Tool>
export PATH=$PATH:<path of Camel K CLI Tool>
source ~/.bashrc
----
+
. Execute the following command to validate that *Camel K* CLI Tool can be utilized on your workstation:
+
----
kamel version
----
+
. Expect to receive the version of the client on your console.
+
[NOTE]
This will install the Camel K operator on the current namespace of your OpenShift Container Platform cluster. In addition, configure the OpenShift Container Platform cluster with the *Camel K* custom resource definitions.

[type=taskResource]
.Custom Resource Definitions in Kubernetes
****
* link:https://docs.okd.io/latest/admin_guide/custom_resource_definitions.html[Kubernetes custom resource definitions, window="_blank"]
****

[type=verification]
Is the *Camel K* CLI Tool installed and usable?


=== Examine the lab assets

. Open a command-line shell.
+
NOTE: For the purposes of these instructions, the local directory for the lab assets is referred to as `$AI_EXERCISE_HOME/camelk/`.

. Execute these commands:
+
----
cd $AI_EXERCISE_HOME/camelk

----
+
. Examine the contents of the folder, by opening each file using your favorite text editor. Note the files contain various implementations of Apache Camel routes.


=== Camel K Operator Installation

* Now, deploy the Camel K operator, which provides the serverless application development framework support. This is an important pre-requisite step to using Camel K on Red Hat OpenShift Container Platform.

. Type this command to begin the installation process:
+
----
kamel install
----
+
. This should be the response:
+
[subs="attributes"]
----
Camel K installed in namespace {user-sanitized-username}-camelk
----

[type=verification]
Were you able to install the operator?

[type=verificationFail]
With help from the instructor, ensure your user account has the appropriate privileges and the resource limits of your user clusterquota has not been reached.


[time=30]
== Build and deploy of Apache Camel Routes

The various implementations of Apache Camel routes (in Javascript, Groovy and Java) will be now be built and deployed for testing.

=== 1. Plain Old Java Object

* Now, update the file `Pojo.java` such that it contains a working Camel route.

. Change working directory to `$AI_EXERCISE_HOME/camelk/`
. Open the file `Pojo.java` using your favorite text editor.
. Add the following code, such that it resides within the `configure` method:
+
----
from("timer:tick?fixedRate=true&period=3000")
      .log("Camel route is active.");

----
+
. Save your changes.
. Begin the build and deployment of the route:
+
----
kamel run Pojo.java --dev

----
+
. The expected results should begin with:
+
----
integration "pojo" created
integration "pojo" in phase Initialization
integration "pojo" in phase Building Kit
integration "pojo" in phase Deploying
integration "pojo" in phase Running
----
. These are five steps involving a successful build and deployment of a Camel route using Camel K.
+
[type=verification]
Were you able to test the Pojo Camel route?
+
. The remainder of the log trace should indicate that Apache Camel is active and using the Java loader. Also, the message `Camel route is active.` should appear with every 3-second interval.
+
----
[1] 2019-11-19 10:50:38.472 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.ContextConfigurer@3c9d0b9d
[1] 2019-11-19 10:50:38.477 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesConfigurer@7ee955a8
[1] 2019-11-19 10:50:38.478 INFO  [main] ApplicationRuntime - Add listener: org.apache.camel.k.listener.RoutesDumper@6ac13091
[1] 2019-11-19 10:50:38.492 INFO  [main] RuntimeSupport - Looking up loader for language: java
[1] 2019-11-19 10:50:38.497 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.java.JavaSourceRoutesLoader@6f96c77 for language java from service definition
[1] 2019-11-19 10:50:38.952 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/Pojo.java?language=java
[1] 2019-11-19 10:50:38.953 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesConfigurer@7ee955a8 executed in phase ConfigureRoutes
[1] 2019-11-19 10:50:38.965 INFO  [main] BaseMainSupport - Using properties from: file:/etc/camel/conf/application.properties
[1] 2019-11-19 10:50:39.267 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.ContextConfigurer@3c9d0b9d executed in phase ConfigureContext
[1] 2019-11-19 10:50:39.268 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) is starting
[1] 2019-11-19 10:50:39.270 INFO  [main] DefaultManagementStrategy - JMX is disabled
[1] 2019-11-19 10:50:39.480 INFO  [main] DefaultCamelContext - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
[1] 2019-11-19 10:50:39.487 INFO  [main] DefaultCamelContext - Route: route1 started and consuming from: timer://tick?fixedRate=true&period=3000
[1] 2019-11-19 10:50:39.491 INFO  [main] DefaultCamelContext - Total 1 routes, of which 1 are started
[1] 2019-11-19 10:50:39.491 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) started in 0.223 seconds
[1] 2019-11-19 10:50:39.492 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesDumper@6ac13091 executed in phase Started
[1] 2019-11-19 10:50:40.505 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Camel route is active.
[1] 2019-11-19 10:50:43.491 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Camel route is active.
[1] 2019-11-19 10:50:46.490 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Camel route is active.
----
+
[type=verification]
Reduce the interval of message display by 2 seconds. Can you make the necessary changes to the Pojo Camel route and redeploy it successfully?

=== 2. Groovy

* Now, deploy a working Camel route implemented in the Groovy language.

. If you have not done so, change working directory to `$AI_EXERCISE_HOME/camelk/`
. Open the file `RandomNumbers.groovy` using your favorite text editor.
. After examining the code, close the editor without making any modifications.
. Begin the build and deployment of the route:
+
----
kamel run RandomNumbers.groovy --dev

----
+
. Observe that random numbers are generated with each time interval:
+
----
[1] 2019-11-19 09:12:22.354 INFO  [main] DefaultCamelContext - Route: groovy started and consuming from: timer://groovy?period=1s
[1] 2019-11-19 09:12:22.356 INFO  [main] DefaultCamelContext - Total 1 routes, of which 1 are started
[1] 2019-11-19 09:12:22.356 INFO  [main] DefaultCamelContext - Apache Camel 3.0.0-RC3 (CamelContext: camel-k) started in 0.185 seconds
[1] 2019-11-19 09:12:22.357 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesDumper@161479c6 executed in phase Started
[1] 2019-11-19 09:12:23.396 INFO  [Camel (camel-k) thread #1 - timer://groovy] info - body: Generating a random number, random-value: -1477281199
[1] 2019-11-19 09:12:24.357 INFO  [Camel (camel-k) thread #1 - timer://groovy] info - body: Generating a random number, random-value: 303538366
[1] 2019-11-19 09:12:25.357 INFO  [Camel (camel-k) thread #1 - timer://groovy] info - body: Generating a random number, random-value: -1596066435
[1] 2019-11-19 09:12:26.357 INFO  [Camel (camel-k) thread #1 - timer://groovy] info - body: Generating a random number, random-value: 955225287
----
+
[type=verification]
Have modifications made to the Camel route such that only one random number appears all the time, from start to finish. Can you make the necessary changes to the Camel route and redeploy it successfully?

=== 3. Complex route implemented in Java

* Now, deploy another Camel route implemented in the Java language. This route simulates the operations (GET, PUT, INVALIDATE) of a key-value cache,

. If you have not done so, change working directory to `$AI_EXERCISE_HOME/camelk/`
. Open the file `KeyValueTest.java` using your favorite text editor.
. After examining the code, close the editor without making any modifications.
. Begin the build and deployment of the route:
+
----
kamel run KeyValueTest.java --dev

----
+
. Observe that keyword `Hello` appears as a result of both the PUT and GET actions:
+
----
[1] 2019-11-19 08:53:23.610 INFO  [main] ApplicationRuntime - Listener org.apache.camel.k.listener.RoutesDumper@161479c6 executed in phase Started
[1] 2019-11-19 08:53:24.626 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action PUT with key 1 is: Hello
[1] 2019-11-19 08:53:24.629 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action GET with key 1 is: Hello
[1] 2019-11-19 08:53:24.630 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Invalidating entry with key 1
[1] 2019-11-19 08:53:24.632 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - The Action GET with key 1 has result? false
[1] 2019-11-19 08:53:25.608 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action PUT with key 1 is: Hello
[1] 2019-11-19 08:53:25.609 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action GET with key 1 is: Hello
[1] 2019-11-19 08:53:25.609 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Invalidating entry with key 1
----
+
[type=verification]
Have modifications made to the Camel route such that the value `true` appears in the line `The Action GET with key 1 has result?` Aim to achieve similar results like this:
+
----
[1] 2019-11-19 08:54:37.449 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - The Action GET with key 1 has result? true
[1] 2019-11-19 08:54:38.447 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action PUT with key 1 is: Hello
[1] 2019-11-19 08:54:38.448 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action GET with key 15 is:
[1] 2019-11-19 08:54:38.448 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Invalidating entry with key 12
[1] 2019-11-19 08:54:38.449 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - The Action GET with key 1 has result? true
[1] 2019-11-19 08:54:39.446 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action PUT with key 1 is: Hello
[1] 2019-11-19 08:54:39.447 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Result of Action GET with key 15 is:
[1] 2019-11-19 08:54:39.447 INFO  [Camel (camel-k) thread #1 - timer://tick] route1 - Invalidating entry with key 12
----

=== 4. Route implemented in Javascript

* Now, deploy another Camel route implemented in the Javascript language.

. If you have not done so, change working directory to `$AI_EXERCISE_HOME/camelk/`
. Open the file `SimpleRoute.js` using your favorite text editor.
. After examining the code, close the editor without making any modifications.
. Begin the build and deployment of the route:
+
----
kamel run SimpleRoute.js --dev

----
+
. Observe that the Javascript `js` loader is used to deploy the Camel route:
+
----
[1] 2019-11-19 11:14:18.345 INFO  [main] RuntimeSupport - Looking up loader for language: js
[1] 2019-11-19 11:14:18.449 INFO  [main] RuntimeSupport - Found loader org.apache.camel.k.loader.js.JavaScriptRoutesLoader@2638011 for language js from service definition
[1] 2019-11-19 11:14:18.622 INFO  [main] RoutesConfigurer - Loading routes from: file:/etc/camel/sources/i-source-000/simple.js?language=js
----
+
. Observe that the exact message is repeated with every time interval.
+
----
[1] 2019-11-19 09:14:18.243 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route js
[1] ]
[1] 2019-11-19 09:14:19.140 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route js
[1] ]
[1] 2019-11-19 09:14:20.140 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route js
[1] ]

----
+
. Add the following code to SimpleRoute.js. This implements a second route called `nodejs`
+
----
from('timer:js?period=2s')
    .routeId('nodejs')
    .setBody()
        .simple('Message generated by route ${routeId}')
    .to('log:info?multiline=true')
----
+
. Redeploy the Camel route.
. Observe the new results:
+
----
[1] 2019-11-19 11:14:20.924 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route nodejs
[1] ]
[1] 2019-11-19 11:14:20.927 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route js
[1] ]
[1] 2019-11-19 11:14:21.925 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route js
[1] ]
[1] 2019-11-19 11:14:22.813 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route nodejs
[1] ]
[1] 2019-11-19 11:14:22.927 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route js
[1] ]
[1] 2019-11-19 11:14:23.926 INFO  [Camel (camel-k) thread #1 - timer://js] info - Exchange[
[1]   ExchangePattern: InOnly
[1]   BodyType: String
[1]   Body: Message generated by route js
----

[type=verification]
Why does the `js` route generates twice more messages than the `nodejs` route with each iteration? What changes are needed to have `js` route generate thrice more messages than `nodejs` in the same iteration?


*Congratulations, you have have completed the Apache Camel K lab!*
